version: '3'
services:
  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=railplanner
      - POSTGRES_USER=railplanner
      - POSTGRES_PASSWORD=railplanner
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data